#
# virtua-lab configuration
#

# configuration settings for digitalocean
digitalocean:

  # digitalocean personal access token for API access
  # see: https://docs.digitalocean.com/reference/api/create-personal-access-token/
  #token: "<paste your personal access token here>"
  token: "dop_v1_0bbca67a638f67b434dae05b3bf13fce9d547222c88d8f900eba250c9d07ab74"

  # target digitalocean region for the lab deployment
  # see: https://docs.digitalocean.com/platform/regional-availability/
  region: "fra1"

  # digitalocean project name
  # see: https://docs.digitalocean.com/products/projects/
  project_name: "virtualab"

  # domain name used for the lab 
  #domain: "example.com"
  domain: "test.hackingnight.ch"

  # the name of the ssh key registered in your digitalocean team
  # see: https://docs.digitalocean.com/platform/teams/upload-ssh-keys/
  ssh_key_name: "terraform"

  # lab network config (virtual private cloud - VPC)
  network:
    vpc_name: "virtualab-network"
    ip_range: "10.113.0.0/24"


  # configuration settings for the jumphost
  jumphost:
    # name of the jumphost droplet
    droplet_name: "jumphost"

    # jumphost droplet size
    # see: https://slugs.do-api.dev/
    droplet_size: "s-4vcpu-8gb-intel"

    # name of the snapshot used when provisioning the jumphost
    snapshot_name: "jumphost-template"

    # the hostname of the jumphost
    # together with the domain, will result e.g. in jumphost.example.com
    hostname: "jumphost"

  # configuration settings for the lab boxes
  labbox:
    # name prefix of the labbox droplets
    droplet_name_prefix: "labbox"

    # labbox droplet size
    # see: https://slugs.do-api.dev/
    droplet_size: "s-2vcpu-4gb"

    # name of the snapshot used when provisioning the labbox droplets
    #snapshot_name: "labbox_template"
    snapshot_name: "kali-template"

    # number of boxes to spin up
    count: 2

    # the hostname prefix of the labboxes
    # together with the domain, will result e.g. in labbox-03.example.com
    hostname_prefix: "labbox"



# configuration settings for guacamole
guacamole: